const CURRICULUM = [
  {
    week: 1,
    title: "认识界面与导航",
    subtitle: "先学会“看”和“动”，别急着建模",
    days: [
      {
        day: 1,
        title: "安装 Blender，认识界面布局",
        time: 30,
        goal: "搞清楚屏幕上每一块区域是干嘛的，不用记住功能，先混个脸熟。",
        tasks: [
          "下载安装最新版 Blender（blender.org 官网）",
          "打开默认场景，认出：3D 视口 / 大纲视图 Outliner / 属性面板 Properties / 时间轴",
          "用鼠标中键拖动、滚轮缩放，随便转动几分钟找找感觉",
        ],
        resource: "Blender 官方手册 - 界面总览",
      },
      {
        day: 2,
        title: "视角导航",
        time: 30,
        goal: "让镜头变成你身体的一部分，之后建模才不会觉得别扭。",
        tasks: [
          "练习数字键盘 1/3/7 切换正视图/侧视图/顶视图",
          "练习 Numpad . （小键盘点）快速聚焦选中物体",
          "尝试 Shift+中键 平移视角，Ctrl+中键 缩放",
        ],
        resource: "关键词搜索：Blender navigation basics",
      },
      {
        day: 3,
        title: "选择与基本变换 G / R / S",
        time: 30,
        goal: "移动、旋转、缩放是使用频率最高的三个操作，练到手不用想。",
        tasks: [
          "点选、框选、Shift 加选/减选物体",
          "练习 G 移动、R 旋转、S 缩放，并尝试按 X/Y/Z 锁定轴向（如 G 再按 X）",
          "尝试输入具体数值，例如 G, X, 2, Enter",
        ],
        resource: "Blender 官方手册 - 基本编辑",
      },
      {
        day: 4,
        title: "添加/删除物体，管理 Outliner",
        time: 30,
        goal: "学会整理场景，为后面复杂项目打基础。",
        tasks: [
          "Shift+A 添加几个基本体（立方体/球/圆柱）",
          "X 删除物体，Ctrl+Z 撤销练习几次别怕手滑",
          "在 Outliner 里新建一个 Collection，把物体拖进去改名字",
        ],
        resource: "Blender 官方手册 - Collections",
      },
      {
        day: 5,
        title: "复习日：拼一个小场景",
        time: 40,
        goal: "只用基本体，摆一个小场景，检验前四天的手感。",
        tasks: [
          "用立方体+球体+圆柱拼一个简单桌面摆件（比如台灯或小房子轮廓）",
          "全程只用 G/R/S 和视角导航完成，不用管好看不好看",
          "保存文件，命名规范一点，比如 day05_scene.blend",
        ],
        resource: "自由练习，无需外部教程",
      },
    ],
  },
  {
    week: 2,
    title: "基础建模",
    subtitle: "进入编辑模式，学会真正“捏”模型",
    days: [
      {
        day: 6,
        title: "编辑模式基础",
        time: 35,
        goal: "认识 Tab 切换、顶点/边/面三种编辑层级。",
        tasks: [
          "Tab 进入/退出编辑模式",
          "数字键 1/2/3 切换 顶点/边/面 选择模式",
          "试着移动几个顶点，观察模型如何变形",
        ],
        resource: "Blender 官方手册 - 网格编辑模式",
      },
      {
        day: 7,
        title: "挤出、内插、倒角",
        time: 40,
        goal: "三个建模核心手法，几乎所有硬表面模型都靠它们。",
        tasks: [
          "E 挤出一个面，观察新几何体的生成",
          "I 内插面，做出一个凹陷或凸起的细节",
          "Ctrl+B 倒角一条边，做出圆润边缘",
        ],
        resource: "关键词搜索：Blender extrude inset bevel tutorial",
      },
      {
        day: 8,
        title: "循环切割 Loop Cut",
        time: 35,
        goal: "学会给模型增加可控的细分线，为后续调整形状做准备。",
        tasks: [
          "Ctrl+R 在立方体上加一条循环切割线，滚轮调整数量",
          "尝试切割后移动这条边线改变模型形状",
          "练习 Ctrl+R 后直接点右键，取消滑移只保留切割",
        ],
        resource: "Blender 官方手册 - Loop Cut and Slide",
      },
      {
        day: 9,
        title: "合并、分离与法线基础",
        time: 35,
        goal: "了解物体之间的关系，以及法线为什么重要（不然渲染会很奇怪）。",
        tasks: [
          "Ctrl+J 合并两个物体成一个",
          "编辑模式下 P 分离部分网格成新物体",
          "打开 Overlay 里的 Face Orientation，认识蓝色（正确）和红色（翻面）",
        ],
        resource: "Blender 官方手册 - Normals",
      },
      {
        day: 10,
        title: "练习日：建一个马克杯或小板凳",
        time: 45,
        goal: "综合运用本周所学，完成第一个“像样”的模型。",
        tasks: [
          "选一个简单物体（马克杯/小板凳/相框任选其一）",
          "用挤出+倒角+循环切割完成主体造型",
          "保存并截图，作为你的第一个作品留念",
        ],
        resource: "关键词搜索：Blender beginner mug modeling",
      },
    ],
  },
  {
    week: 3,
    title: "修改器与高效编辑",
    subtitle: "用修改器代替重复劳动，事半功倍",
    days: [
      {
        day: 11,
        title: "修改器面板 + Mirror 镜像",
        time: 30,
        goal: "认识修改器堆栈的概念，学会对称建模。",
        tasks: [
          "打开属性面板的扳手图标（Modifier Properties）",
          "给一个物体添加 Mirror 修改器，观察对称效果",
          "尝试只建一半模型，靠镜像完成整体",
        ],
        resource: "Blender 官方手册 - Mirror Modifier",
      },
      {
        day: 12,
        title: "细分曲面 Subdivision Surface",
        time: 30,
        goal: "了解低模+细分的工作流程，让模型瞬间变光滑。",
        tasks: [
          "给立方体加 Subdivision Surface 修改器，调整层级观察变化",
          "开关 Edit Mode Display，理解“控制网格”和“最终效果”的区别",
          "配合倒角权重（Edge Crease）做出既圆润又保留硬边的效果",
        ],
        resource: "关键词搜索：Blender subdivision surface workflow",
      },
      {
        day: 13,
        title: "阵列修改器 Array",
        time: 30,
        goal: "学会用一个物体快速复制出一排/一圈结构。",
        tasks: [
          "给一个立方体加 Array 修改器，调整数量和偏移",
          "尝试做一排栅栏或一段楼梯的雏形",
          "试试叠加 Array + Mirror 做出更复杂的重复结构",
        ],
        resource: "Blender 官方手册 - Array Modifier",
      },
      {
        day: 14,
        title: "实体化 Solidify + Bevel 修改器",
        time: 30,
        goal: "把薄面变成有厚度的实体，并自动处理倒角细节。",
        tasks: [
          "对一个平面加 Solidify，做出一块木板的厚度感",
          "加 Bevel 修改器，自动给所有边缘加小圆角，观察渲染质感的变化",
          "调整修改器顺序（拖拽），看看顺序不同结果有什么差别",
        ],
        resource: "Blender 官方手册 - Solidify / Bevel Modifier",
      },
      {
        day: 15,
        title: "练习日：用修改器做一个书架或机械零件",
        time: 45,
        goal: "综合本周修改器知识，感受“非破坏性建模”的效率。",
        tasks: [
          "选一个有重复结构的物体（书架格子/螺母/散热片）",
          "至少组合使用两种修改器完成造型",
          "保存文件并记录你用到的修改器组合，方便以后复用",
        ],
        resource: "自由练习，可参考前几日笔记",
      },
    ],
  },
  {
    week: 4,
    title: "材质、着色与灯光",
    subtitle: "让灰色模型第一次“活”起来",
    days: [
      {
        day: 16,
        title: "材质基础与 Principled BSDF",
        time: 30,
        goal: "认识 Blender 最核心的万能材质节点。",
        tasks: [
          "给物体新建一个材质，切换到 Shading 工作区看节点",
          "调整 Base Color，观察视口实时预览（记得切到 Material Preview 模式）",
          "了解 Principled BSDF 里 Metallic 和 Roughness 两个关键参数",
        ],
        resource: "Blender 官方手册 - Principled BSDF",
      },
      {
        day: 17,
        title: "参数练习：颜色/粗糙度/金属度",
        time: 30,
        goal: "用同一个模型做出塑料、金属、陶瓷三种不同质感。",
        tasks: [
          "复制同一个物体三份",
          "分别调出：哑光塑料感、拉丝金属感、光滑陶瓷感三种材质",
          "对比三者的 Roughness / Metallic 数值差异，记下心得",
        ],
        resource: "关键词搜索：Principled BSDF roughness metallic comparison",
      },
      {
        day: 18,
        title: "UV 展开入门",
        time: 35,
        goal: "了解贴图前必须做的准备工作——UV 展开。",
        tasks: [
          "选中一个简单模型，编辑模式全选后 U 打开 UV 菜单",
          "尝试 Smart UV Project 快速展开",
          "打开 UV Editing 工作区，看看展开后的效果长什么样",
        ],
        resource: "Blender 官方手册 - UV Editing",
      },
      {
        day: 19,
        title: "灯光类型与三点布光法",
        time: 35,
        goal: "学会用光影讲故事，这是让作品好看的关键一步。",
        tasks: [
          "依次添加 Point / Sun / Area / Spot 四种灯光，感受区别",
          "用一盏主光 + 一盏辅光 + 一盏轮廓光，搭出经典三点布光",
          "调整灯光强度和颜色，观察物体质感的变化",
        ],
        resource: "关键词搜索：Blender three point lighting tutorial",
      },
      {
        day: 20,
        title: "练习日：给作品上材质和灯光",
        time: 45,
        goal: "把第10天或第15天做的模型“救活”。",
        tasks: [
          "挑一个之前做的模型，给每个部件分配合适的材质",
          "布置三点光，调出一个满意的视角",
          "截图保存，对比最初的灰模，感受进步",
        ],
        resource: "自由练习",
      },
    ],
  },
  {
    week: 5,
    title: "摄像机、渲染与基础动画",
    subtitle: "从静态模型走向“成片”",
    days: [
      {
        day: 21,
        title: "摄像机设置与构图",
        time: 30,
        goal: "学会用摄像机取景，而不是永远用默认视角截图。",
        tasks: [
          "Shift+A 添加摄像机，Ctrl+Numpad0 切换到摄像机视角",
          "用 N 面板里的 View > Camera to View，方便边转视角边取景",
          "了解三分法构图，试着把主体放在三分线交点上",
        ],
        resource: "Blender 官方手册 - Camera",
      },
      {
        day: 22,
        title: "渲染引擎与渲染设置",
        time: 30,
        goal: "了解 Eevee 和 Cycles 的区别，学会导出第一张成品图。",
        tasks: [
          "在渲染属性里切换 Eevee 和 Cycles，对比速度和效果差异",
          "设置输出分辨率和文件格式（PNG）",
          "Render > Render Image 渲染并导出一张静帧",
        ],
        resource: "Blender 官方手册 - Render Engines",
      },
      {
        day: 23,
        title: "关键帧动画基础",
        time: 35,
        goal: "理解关键帧是动画的最小单位。",
        tasks: [
          "在时间轴第1帧给物体位置打关键帧（I 键）",
          "跳到第30帧，移动物体再打一次关键帧",
          "拖动时间轴播放，观察物体自动补间移动",
        ],
        resource: "Blender 官方手册 - Keyframes",
      },
      {
        day: 24,
        title: "简单动画曲线入门",
        time: 35,
        goal: "让动画不再是死板的匀速运动。",
        tasks: [
          "打开 Graph Editor，观察刚才动画的曲线形状",
          "尝试把插值方式从 Bezier 改成 Linear 或 Ease，对比运动感觉",
          "给物体加一个简单的旋转动画，叠加在位移之上",
        ],
        resource: "关键词搜索：Blender animation curves basics",
      },
      {
        day: 25,
        title: "练习日：渲染静帧 + 制作3秒动画",
        time: 45,
        goal: "第一次完整走完“建模-布光-渲染-动画”的流程。",
        tasks: [
          "为本周的场景渲染一张成品静帧图",
          "制作一个3秒左右的小动画（物体转个圈或移动一小段）",
          "导出动画为视频或图片序列",
        ],
        resource: "自由练习",
      },
    ],
  },
  {
    week: 6,
    title: "综合小项目与复盘",
    subtitle: "用一个完整作品，串起前五周所有知识",
    days: [
      {
        day: 26,
        title: "小项目 Day1：确定主题与建模",
        time: 40,
        goal: "选一个不太复杂的主题（书房一角/卡通小房子/桌面摆件组合）。",
        tasks: [
          "花5分钟画个简单草图或找1-2张参考图",
          "搭建场景的大致布局（几个主要物体的位置）",
          "完成其中1-2个物体的详细建模",
        ],
        resource: "自由创作",
      },
      {
        day: 27,
        title: "小项目 Day2：完成建模",
        time: 40,
        goal: "把场景里剩余的物体都建出来。",
        tasks: [
          "继续完成场景中其余物体的建模",
          "适当使用修改器提高效率",
          "检查比例是否协调，必要时调整大小和位置",
        ],
        resource: "自由创作",
      },
      {
        day: 28,
        title: "小项目 Day3：材质与灯光",
        time: 40,
        goal: "让整个场景在视觉上统一、好看。",
        tasks: [
          "为所有物体分配材质",
          "布置符合场景氛围的灯光（暖光/冷光/顶光皆可）",
          "调整摄像机构图，选一个最满意的视角",
        ],
        resource: "自由创作",
      },
      {
        day: 29,
        title: "小项目 Day4：渲染与精修",
        time: 40,
        goal: "完成最终成品图。",
        tasks: [
          "微调材质和灯光细节",
          "渲染最终成品图（可以渲染2-3个角度）",
          "导出并保存，这是你一个月学习的毕业作品",
        ],
        resource: "自由创作",
      },
      {
        day: 30,
        title: "复盘与规划下一步",
        time: 30,
        goal: "回顾一个月的进步，规划继续学习的方向。",
        tasks: [
          "把第1天和第30天的作品放在一起对比一下",
          "写下这一个月里最有成就感和最卡壳的地方",
          "选择下一阶段方向：人物建模 / 硬表面机械 / 动画进阶 / 材质贴图深入，任选其一继续学",
        ],
        resource: "自由复盘",
      },
    ],
  },
];
